### PR TITLE
Static link

### PR DESCRIPTION
**Pull request by sj26**
This doesn't seem to have much effect for windows or mac, but it stops linux from dynamically linking libc so we can restore Debian 7 compatibility. It doesn't seem to add a huge about of weight to the binary.

If all good I'll backport to 2-1-stable.

### CODE REVIEW

**Comment by toolmantim** [comment]
:+1: I think this is a good idea

**Comment by sj26** [comment]
## Before

**Comment by sj26** [comment]
### Before

screenshot 2016-03-09 22 19 44

### After

screenshot 2016-03-09 22 19 57

**Comment by keithpitt** [comment]
Sounds great to me! :+1:

**Pull request merged**
