### PR TITLE
Prune when fetching with a refspec

### PR DESCRIPTION
**Pull request by cysp**
https://github.com/buildkite/agent/issues/507

The `Fetch and checkout commit` codepath (the last one) is the one that I actually saw the problem affect and this change fix, but the other paths look like they might get caught by the same scenario.
I left the `refs/pull/…/head` and `commit-sha` fetches unchanged because I figure that they wouldn't need the pruning.

### CODE REVIEW

**Comment by keithpitt** [comment]
Ah cool, thanks for the change! Which versions of Git is `--prune` available in? Do we need to do any sort of version checking?

**Comment by keithpitt** [comment]
@sj26 has done a ton of work in that section of the bootstrap, so I'll let him chime in and see if it's cool to merge. But looks OK to me! 👌

**Comment by cysp** [comment]
I took a look at when it was introduced and saw that it was eight years ago so figured it would be okay.
https://github.com/git/git/commit/f360d844de4b752b4cba2343b95592ae4d55d09a

Is that okay?

**Comment by keithpitt** [comment]
Oh yeah, I think that's totally fine (I was just wondering because if was a feature included with the latest release of Git, it'd be hard to get everyone to convert). I'm actually not sure what our lowest supported version is, but we should find out and make that clear in the bootstrap!

**Comment by sj26** [comment]
We should backport this to 2-6-stable in the bootstrap.sh, too.

**Comment by lox** [comment]
Thanks @cysp!

**Comment by pda** [comment]
Thanks — I just ran into this issue, saves a pull request ;)

**Pull request merged**
