### PR TITLE
Move bootstrap to top level subpackage

### PR DESCRIPTION
**Pull request by lox**
As part of learning my way around the agent codebase, I did some minor refactoring. I'm completely happy for these to be rejected, they don't do much beyond consolidate some things and move some things around.

* `agent/bootstrap` moves to the top level `bootstrap` package.
* `shell/process` moves into `bootstrap/subprocess` to make it's intent and use-case clearer
* Removed an unused error return from `shell.EnvironmentFromSlice`. 
* Copy the std library `exec.LookPath` rather than using the env locking stuff in `bootstrap.subprocess`. 

Wrote this on 🌴 so take with a grain of salt :)

### CODE REVIEW

**Comment by keithpitt** [comment]
This salt is tasty! Once the build is green I'll do a proper review and then we can have a merge party!

**Comment by lox** [comment]
Cool, fixed @keithpitt. I finally got my IDE to not remove imports that are only in vendors :)

**Comment by lox** [comment]
:shipit: ?

**Comment by keithpitt** [comment]
:rocket:

**Pull request merged**
