### PR TITLE
Set the content encoding on artifacts uploaded to s3

### PR DESCRIPTION
**Pull request by airhorns**
This sucker isn't fully tested yet, wanted to get buy in on the approach before doing the leg work :)

We (Shopify) upload a whackload of artifacts to s3 using the buildkite agent, and have started to need to compress some of the bigger ones. We're working on a bunch of coverage stuff and other test time instrumentation who's artifacts can get really, really big at the highest fidelity, so we gzip them after we produce them and before they get uploaded. This is all well and good and Buildkite doesn't have to care, but, we also want to start doing useful stuff with them after they're uploaded! 

S3 serves them, and it gets the mime type right (or I guess as right as you can be for a `csv.gz` file), but it doesn't set a `Content-Encoding` header when it serves the file. Technically, it's fine to serve a gzipped stream without specifying that that is how the stream is compressed, but, it breaks consumers that aren't smart enough to know the thing is gzipped. We have one such consumer which is a codebase we don't really control and don't really want to couple to our file naming format (Neo4j). It uses the `Content-Encoding` to know how do decode the incoming stream and if it should decompress, and since S3 doesn't set the encoding unless you tell it to, it doesn't do any decoding, and we end up with compressed gobbledegook in the database.

So, I'd love it if the agent did the same kind of profiling that it does for the mime type for the content encoding, and set that in the s3 options for the put. That way, S3 would serve the blob with the right content encoding, and any downstream consumers (like neo4j or the browser for that matter) would consume knowing that it had to decompress.

What do y'all think of the idea? And if you like it, where should I put the code that does this profiling? I did a simple version to illustrate but I'm not the best go programmer so feel free to tell me how it can be better and how to test.

Thanks!

### CODE REVIEW

**Comment by lox** [comment]
Sounds like a great idea!

**Comment by airhorns** [comment]
Ok, questions for moving forward then:

 - Is it ok to land the logic that guesses at a content encoding in the agent's `mime` module? It's not really a mime related thing, but I like putting it somewhere other than the s3 uploader
 - Is there a way to mock the whole upload process so I can write a test that actually executes the code in question? Looks like there isn't one for the flow yet
 - Any tips on testing this locally? I can bootstrap my environment and run the agent but should I just be able to invoke the upload task?

**Comment by lox** [comment]
I just merged https://github.com/buildkite/agent/pull/474 in, which brings in the latest aws sdk. I resolved conflicts as best as I could. 

I'd love to get your PR merged and I will do some manual testing. You should absolutely be able to run the agent locally if you have AWS credentials setup and a custom s3 bucket. Check out https://buildkite.com/docs/agent/cli-artifact#using-your-own-s3-bucket

**Comment by airhorns** [comment]
Ok, I ran a test successfully locally and uploaded an artifact, so awesome, but then pulled and merged in the AWS SDK changes as well as the hotfix branch up to 13c0739 and am now getting segfaults with what worked before. Same issue as mentioned over there with the `AWS_REGION` env var, but, I actually set it to `us-east-1` locally and still get a segfault. Here's the stack:

```
OTT-HarryBrundage ~/C/g/s/g/b/agent (gzip-content-type) ➜
go run main.go artifact upload ~/Code/wedge-viewer/artists.csv.gz s3://shopify-test/buildkite-upload-test
2017-06-27 17:46:09 INFO   Found 1 files that match "/Users/hornairs/Code/wedge-viewer/artists.csv.gz"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13cec13]

goroutine 1 [running]:
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x198bcef, 0x19, 0x921e0, 0x1ef1cc0, 0x18b9340, 0x18b9340)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:26 +0x153
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x1, 0x1ef2960, 0x21af280, 0x10000c420000340, 0xc4201ddcc8)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:133 +0x58
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc4201991d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21af280, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:89 +0x65
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc420199230, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x18c5400, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:77 +0xc9
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc420071b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:208 +0x13a
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.Signer.signWithBody(0xc420071b00, 0x0, 0x1e8e4e0, 0xc42000e1b8, 0x10100, 0x19acb58, 0x0, 0xc42000b800, 0x1e92da0, 0xc4201a9960, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:338 +0x259
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.signSDKRequestWithCurrTime(0xc4201be800, 0x19acb58, 0x0, 0x0, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:472 +0x2f4
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.SignSDKRequest(0xc4201be800)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:416 +0x52
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc4201be970, 0xc4201be800)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:164 +0x87
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc4201be800, 0x19ab640, 0xc4201be800)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:337 +0xb0
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc4201be800, 0x0, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:474 +0x13d
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjects(0xc42000e1d0, 0xc4201ec400, 0x0, 0x0, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:3887 +0x4d
github.com/buildkite/agent/agent.newS3Client(0x7fff5fbff6de, 0xc, 0xc, 0xc420010f01, 0xc4201babb0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/agent/s3.go:108 +0x55c
github.com/buildkite/agent/agent.(*S3Uploader).Setup(0xc4201a9020, 0x7fff5fbff6d9, 0x27, 0x0, 0x1976c01, 0x4)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/agent/s3_uploader.go:35 +0x6e
github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc4201ec100, 0xc42000e1b0, 0x1, 0x1, 0x2, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/agent/artifact_uploader.go:152 +0x13f
github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc4201ec100, 0x1e, 0xc4200100bd)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/agent/artifact_uploader.go:47 +0x212
github.com/buildkite/agent/clicommand.glob..func5(0xc4201bc8c0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/clicommand/artifact_upload.go:91 +0x297
github.com/buildkite/agent/vendor/github.com/urfave/cli.HandleAction(0x17c66a0, 0x19ab520, 0xc4201bc8c0, 0xc420071800, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:487 +0x7c
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0x1979530, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199677e, 0x23, 0x0, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4201469c0, 0xc4201bc640, 0x0, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.startApp(0x197b06b, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199d134, 0x2d, 0x0, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:293 +0x8a3
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0x197b06b, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199d134, 0x2d, 0x0, ...)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:93 +0x14c7
github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).Run(0xc420146820, 0xc420010230, 0x5, 0x5, 0x0, 0x0)
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/Users/hornairs/Code/go/src/github.com/buildkite/agent/main.go:102 +0x565
exit status 2
```

**Comment by lox** [comment]
This was a regression I accidentally introduced 😱! Fixed in https://github.com/buildkite/agent/pull/497

**Comment by airhorns** [comment]
@lox I double checked to make sure by merging master again, but even with #497 merged that SIGSEGV is still happening with the `AWS_REGION` variable set. Then, I realized I hadn't re-set my environment variables for AWS authentication (`BUILDKITE_S3_ACCESS_KEY_ID` etc), and when I set them, the upload worked again which is great news, so this PR is good to go. But, the above exception is in fact still possible to hit on master if you don't have S3 access creds in the environment before starting the s3 session. I am not sure why that would be because it looks like it should panic earlier when those env vars aren't found, but you might know better :)

**Comment by lox** [comment]
Investigating this today @airhorns!

**Comment by lox** [comment]
I've had a go at reproducing the panic on master, having a hard time doing so. This PR looks good to go, so I will keep going with it in master. Thanks for the hard work!

**Pull request merged**
