### PR TITLE
Option to automatically accept RSA fingerprints when git cloning.

### PR DESCRIPTION
**Pull request by keithpitt**
This change will allow the agent to automatically accept the RSA fingerprints when cloning from an ssh based git repository:

image

- [ ] Add support for `BUILDKITE_REPO_SSH_HOST` on buildkite.com
- [ ] Decide on the right argument name. Is `--no-ssh-keyscan` correct? Or is there another name? `--no-ssh-accept` or something?

### CODE REVIEW

**Comment by toolmantim** [comment]
`--no-ssh-keyscan` sounds right!

**Comment by toolmantim** [comment]
I guess that'd go with `--scripts-only` for security-restricted setups, once we do arbitrary command execution…

**Comment by keithpitt** [comment]
The only thing is, if we come up with a better way (instead of keyscan) then the option becomes wrong. `--no-ssh-rsa-accept` maybe?

**Comment by toolmantim** [comment]
Yeah good point. What about `--no-ssh-key-detection` or `--disable-ssh-key-detection`

**Comment by keithpitt** [comment]
I'm gonna run with `--no-ssh-fingerprint-verification` I think, it's a bit long, but it seems like the language that https://help.github.com/articles/generating-ssh-keys/ uses.

**Comment by toolmantim** [comment]
hrmm… reading it now, it sounds like it disables SSH clone's fingerprint detection altogether. Perhaps `--no-automatic-ssh-fingerprint-verification` or `--disable-automatic-ssh-fingerprint-verification`

**Comment by keithpitt** [comment]
`--no-automatic-ssh-fingerprint-verification` :D:D

**Comment by toolmantim** [comment]
`--please-do-not-attempt-to-automatically-verify-an-ssh-hosts-keys-fingerprint-mmkay`

**Pull request merged**
