### PR TITLE
Add health check endpoint

### PR DESCRIPTION
**Pull request by wolfeidau**
This is the health check we discussed.

I have the basic health check working, I need to add a flag, rejig the structure and add some tests.

The aim is to expose the last job, and it's status and the last api request and it's status.

Ideally you would add some other information as requested in the future.

Looks like: 

```json
{
  "lastApiCall": {
    "status": "POST https://agent.buildkite.com/v2/register got response with status 200 OK",
    "timeTaken": "1.421656691s"
  }
}
```

### CODE REVIEW

**Comment by keithpitt** [comment]
Awesome! With the port thing, how does that work when you have multiple agents installed on the same machine?

**Comment by wolfeidau** [comment]
To start with it may be better to leave this off by default.

My plan is to add a switch to enable it and change the bind address, this lets people with many agents bind them on different ports if required, or just do nothing and it won't bind any of them.

Switch is an empty string by default, and can be overridden at the command line, so `:9090` as an example.

As you would have to configure something to monitor the state of the health check it doesn't seem to much to request the user also enable it.

**Comment by keithpitt** [comment]
I'm going to close this until we can both find some time to take another crack at it @wolfeidau! :dancers:

**Comment by keithpitt** [comment]
Thanks for the work you've done on it so far! :heart:

**Comment by wolfeidau** [comment]
Yeah agreed maybe when you come back to Australia!?

**Comment by keithpitt** [comment]
Sounds good!

**Pull request closed without merging**
