### PR TITLE
Added linux,ppc64le as valid build target.

### PR DESCRIPTION
**Pull request by derekmarcotte**
Cannot build on linux ppc64le, and wish to.  Seems to work fine with this.

### CODE REVIEW

**Comment by lox** [comment]
Thanks, seems to make sense! What systems are `ppc64le`?

**Comment by derekmarcotte** [comment]
Hrm, good question!  IBM p-series?  Mainly, it's the [native CI environment](https://github.com/derekmarcotte/kitefactory) I'm building for use by the [node_exporter](https://github.com/prometheus/node_exporter) project.  I'm not sure who is running node_exporter on Linux Power, and for what purposes though.

**Comment by lox** [comment]
Kitefactory looks super cool!

**Comment by lox** [comment]
Drop us an email at hello@buildkite.com if we can help @derekmarcotte!

**Pull request merged**
