### PR TITLE
Avoid pausing after job has finished

### PR DESCRIPTION
**Pull request by sj26**
When we run a job we start two background goroutines — one polling for new logs to upload, and the other polling the job status to see if a job is cancelled during execution. They sleep in between polling. The job status sleep interval is set by buildkite.com through the agent api, and starts at 5 seconds increasing to 30 seconds when there are many agents connected. So these goroutines may sleep for up to 30 seconds.

When a job finishes, we tell the Buildkite agent api that the job is finished, then we wait for these background goroutines to exit. In the meantime, the Buildkite agent api might notice we're no longer running a job — we finished it — and assign us new work to do, but we're still waiting on those goroutines to finish for up to 30 seconds.

This change creates a context to pass into the goroutines which can be cancelled, makes sure that when we sleep in the goroutines we are also listening for a cancellation, and cancels the context when the job is finished to wakeup the goroutines, avoiding the up-to-30-second wait.

### CODE REVIEW

**Comment by sj26** [comment]
@keithpitt one more adjustment — we can move the job finish down slightly to make sure that everything has finished before we.. finish.

**Comment by keithpitt** [comment]
@sj26 is this minor-version-releasable?

**Comment by keithpitt** [comment]
Actually, we're probably due for 3.2 with the other changes we've made!

**Comment by sj26** [comment]
@keithpitt yeah, it's a fix, doesn't introduce new functionality or deprecate any current functionality, so I reckon it's a patch release. We've shipped a 3.1.2 beta.

**Pull request merged**
