### PR TITLE
Wait for line callbacks to finish before finishing process

### PR DESCRIPTION
**Pull request by keithpitt**
We have a potential race condition when uploading header times to BK. I believe the follow backtrace is saying: "You tried to call .Add() on a wait group that is already waiting".

Looking a the stack trace `[HeaderTimesStreamer] Waiting for all the lines to be scanned` is called, then another header time is found, so I believe the line callbacks are still being fired even after the process has finished.

This change ensures that all the line callbacks have fired before finishing the process. Even if the line callback in itself fires off another go-routine that's ok, because that code usually has it's own waiters setup.

```
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [LineScanner] Encountered EOF
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [LineScanner] Finished
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 INFO   Process with PID: 29576 finished with Exit Status: 0
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [Process] Waiting for routines to finish
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [Process] PTY has finished being copied to the buffer
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [HeaderTimesStreamer] Waiting for all the lines to be scanned
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [HeaderTimesStreamer] Found header "\x1b[0m~~~ Running global post-command hook"
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [HeaderTimesStreamer] Found header "~~~ Running local post-command hook"
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: panic: sync: WaitGroup is reused before previous Wait has returned
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: goroutine 1 [running]:
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: panic(0x784440, 0xc420407c80)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: sync.(*WaitGroup).Wait(0xc4202c0878)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /usr/local/go/src/sync/waitgroup.go:133 +0xfe
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/agent.(*HeaderTimesStreamer).Stop(0xc4202c0840)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/agent/header_times_streamer.go:127 +0x69
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/agent.(*JobRunner).Run(0xc4202c07e0, 0x0, 0xc420405920)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/agent/job_runner.go:109 +0x250
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/agent.(*AgentWorker).Ping(0xc42015c4e0)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/agent/agent_worker.go:273 +0x4b5
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/agent.(*AgentWorker).Start(0xc42015c4e0, 0xc4203fd760, 0x0)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/agent/agent_worker.go:85 +0x18b
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/agent.(*AgentPool).Start(0xc420052680, 0xc42000cae0, 0xc42010e1a0)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/agent/agent_pool.go:81 +0x5bf
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/clicommand.glob..func1(0xc420086580)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/clicommand/agent_start.go:230 +0x3cf
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/vendor/github.com/codegangsta/cli.Command.Run(0x80e4d5, 0x5, 0x0, 0x0, 0x81730d, 0x18, 0x827fa4, 0x1c1, 0x0, 0x0, ...)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/vendor/github.com/codegangsta/cli/command.go:101 +0x6e9
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: github.com/buildkite/agent/vendor/github.com/codegangsta/cli.(*App).Run(0xc42010a000, 0xc42000a120, 0x2, 0x2, 0x0, 0x0)
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/vendor/github.com/codegangsta/cli/app.go:125 +0x64b
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: main.main()
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: /go/src/github.com/buildkite/agent/main.go:100 +0x401
Nov 24 23:42:31 buildkite-agent-b06ec88b systemd: buildkite-agent.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 24 23:42:31 buildkite-agent-b06ec88b systemd: Unit buildkite-agent.service entered failed state.
Nov 24 23:42:31 buildkite-agent-b06ec88b systemd: buildkite-agent.service failed.
Nov 24 23:42:36 buildkite-agent-b06ec88b systemd: buildkite-agent.service holdoff time over, scheduling restart.
```

### CODE REVIEW

**Comment by keithpitt** [comment]
@sj26 would you be able to review this for me when you get a chance? I think this fix should work, but it's a little gnarly.

**Comment by sj26** [comment]
I think maybe your `lineCallbackWaitGroup.Wait()` should go before the `waitGroup.Done()` within the `LineScanner` on [line 179](https://github.com/buildkite/agent/blob/42bf54834b1754cd1cd1ce37ce8463b289060f0e/process/process.go#L179), otherwise we're skipping another timeout.

If io.Copy is never returning from some builds and we're seeing some goroutines never finish / reach waitGroup.Done then we probably also probably seeing memory leaks...

**Comment by sj26** [comment]
There are similar races in the start callback, too...

Perhaps instead of callbacks we should be using channels?

**Comment by keithpitt** [comment]
I have no idea how to channel :P if you can think of a better way go for it!

Can you see the problem? It was a little tricky to get my head around...

**Comment by keithpitt** [comment]
@sj26 I've made that suggested change!

**Pull request merged**
