### PR TITLE
Add a config option to retry checkouts

### PR DESCRIPTION
**Pull request by lox**
There are several situations in which checkouts can be flakey, sometimes it's a overloaded central server and sometimes it's something like XCode being slow to release file locks (causing git clean to fail). 

This adds a generalized exponential backoff on checkouts. It is off by default.

### CODE REVIEW

**Comment by jgavris** [comment]
We build an Xcode project (putting its DERIVED_DATA_PATH) in the git repository. Sometimes builds are interrupted because we're pushing new code to that branch, and Xcode is a little slow at unlocking all the build files. When the next job starts, git fails to complete the checkout because of the locked files. We've been manually retrying this for a while, but it is fairly annoying. Because this step runs before we get a chance to intervene, this fix needs to placed here. Thanks!

**Comment by keithpitt** [comment]
@lox oh cool, any reason why this isn't just built in by default?

**Comment by jgavris** [comment]
@keithpitt what’s a reasonable default?

**Comment by keithpitt** [comment]
@jgavris as in, instead of having to "opt-in" to retries, it's just part of the default checkout process. I can't think of an example where you _wouldn't_ want us to retry if it fails?

**Comment by keithpitt** [comment]
Perhaps if the repository is _really_ large, and doing another checkout is really slow - then it could be a bad idea? But the job will fail anyway, and someone will login to BK, see the result and be like "eughhh stupid internet" and just hit retry. At least if we retry by default that'll save them a step?

**Comment by keithpitt** [comment]
Oh, also what's the behaviour when a checkout fails because of a security check?

**Comment by lox** [comment]
The most common failure would be not having permission to checkout a repository, in which case I reckon a retry would be pretty annoying.

**Comment by lox** [comment]
We've seen checkouts fail from Phabricator due to the server being overwhelmed. 

I dunno, I'd tend to have this off by default initially. I think it's a solution to an uncommon problem that has the side effect of making permissions errors much slower to fail.

**Comment by jgavris** [comment]
I'm totally fine with turning this on in the config...our linux build agents for instance probably won't need this behavior.

**Comment by keithpitt** [comment]
> The most common failure would be not having permission to checkout a repository, in which case I reckon a retry would be pretty annoying.

Totally. In that case, could we perhaps inspect the output of the checkout and not do a retry?

**Comment by keithpitt** [comment]
I'm just trying to avoid configurations where users contact us and email support with "I have this problem" and we're like "oh, go turn this thing on". When ever I have problem with software, my first point of call isn't usually looking in the config for a magical flag to change.

(I'm just trying to make my case that this should just be on by default no config. I think the change is a really good one)

**Comment by lox** [comment]
> I'm just trying to avoid configurations where users contact us and email support with "I have this problem" and we're like "oh, go turn this thing on". When ever I have problem with software, my first point of call isn't usually looking in the config for a magical flag to change.

Yup, totally on the same page with avoiding proliferation of knobs and dials. I just suspect there are enough completely common reasons for a checkout to fail that we will have a hard time catching them all. I guess it would be pretty annoying to get retries for some of the common ones if you turned this on regardless of whether it's default or not.

**Comment by jgavris** [comment]
If you could catch more specifically the `git clean` portion, that would probably be safe to retry a few times?

**Comment by jgavris** [comment]
Can we try this out as opt-in for a release / version?

**Comment by lox** [comment]
We'll ship this in the next beta as an "experiment". Will do a write up on how to enable it when we ship it @jgavris. Thanks for your patience, all going well this will either become a default or a config option in the v3 stable release.

**Comment by jgavris** [comment]
Is it possible to install the beta from homebrew?

**Pull request merged**
