### PR TITLE
Update launchd templates to use .buildkite-agent dir

### PR DESCRIPTION
**Pull request by julianwa**
Should match dir structure created by https://raw.githubusercontent.com/buildkite/agent/master/install.sh

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks for the catch here!

**Comment by julianwa** [comment]
NP. Should also update these docs:

https://buildkite.com/docs/agent/osx#starting-on-login

`s/LaunchAgent/LaunchAgents/`
`s/.buildkite/.buildkite-agent/`

**Comment by toolmantim** [comment]
Thanks! I've just fixed those in buildkite/docs@a2570cd3342610269bd93bd69a6a1e6000e9209f and buildkite/docs@a2570cd3342610269bd93bd69a6a1e6000e9209f, and it's been updated on https://buildkite.com/docs/agent/osx - let me know if that all looks good :+1:

**Comment by julianwa** [comment]
LGTM, thanks! (Sorry, didn't realize the docs were in the repo or I would have included in my PR.)

One other note: it's not clear that the `sudo`s are necessary since all of the files affected should be owned by the current user.

**Comment by toolmantim** [comment]
:+1: No worries, they're a separate repo anyhoo. And I've removed those `sudo`s now too, nice catch (again)

**Pull request merged**
