### PR TITLE
Add godep requirement to getting started section in readme

### PR DESCRIPTION
**Pull request by SomeoneWeird**

### CODE REVIEW

**Comment by keithpitt** [comment]
We actually don't use `godep` in the agent project! We used to, but now we just add the `vendor` path to the `$GOPATH`. We'll probably switch to using the built in go vendor stuff eventually: https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit?pli=1

**Comment by SomeoneWeird** [comment]
Oh, that's super weird. Stuff wouldn't build unless I run the `godep get` command. *shrug*

**Comment by keithpitt** [comment]
Perhaps try this:

```
brew install direnv
cp .envrc-sample .envrc
direnv allow
```

**Comment by SomeoneWeird** [comment]
Aha. Many thanks :)

**Pull request closed without merging**
