### PR TITLE
add netbsd to the build matrix

### PR DESCRIPTION
**Pull request by yob**
Prompted by the discussion in #1431

### CODE REVIEW

**Review by ticky — APPROVED** [review]
Finally, I can get to work on the Buildkite Agent port to the PlayStation 2 😂

**Comment by ibuclaw** [comment]
@yob, thanks.  Is there a nightly binary that you'd like me to test?  My netbsd VM is currently connected [here](https://buildkite.com/d-programming-gdc/gcc/builds/277#a1414961-317c-486a-a713-f379d7a1233d).

**Comment by yob** [comment]
That would be great, cheers!

The latest netbsd nightly is available at: https://download.buildkite.com/agent/experimental/3.30.0-beta.1.3855/buildkite-agent-netbsd-amd64

**Comment by yob** [comment]
Seems like it's working well. Thanks for testing it :heart:

**Pull request merged**
