### PR TITLE
Add a pipeline parse command

### PR DESCRIPTION
**Pull request by toolmantim**
For https://github.com/toolmantim/bksr I'd like to be able to support the env interpolation that the agent does, as well as inherit the pipeline config search paths, and a few other things that are built into the agent. This adds a new pipeline parse command to help other tools that might want to process pipelines:

```
$ go run main.go pipeline parse
Usage:

   buildkite-agent pipeline parse <file> [arguments...]

Description:

   Prints to STDOUT the parsed pipeline as JSON.

Example:

   $ buildkite-agent pipeline parse
   $ buildkite-agent pipeline parse my-custom-pipeline.yml
   $ ./script/dynamic_step_generator | buildkite-agent pipeline parse

Options:

   --no-color  Don't show colors in logging [$BUILDKITE_AGENT_NO_COLOR]
   --debug     Enable debug mode [$BUILDKITE_AGENT_DEBUG]
```

Example output, for the agent repo:

```
$ env BUILDKITE_COMMIT=commit123 BUILDKITE_BRANCH=branch123 BUILDKITE_MESSAGE=message123 go run main.go pipeline parse
2018-05-13 22:46:29 INFO   Searching for pipeline config...
2018-05-13 22:46:29 INFO   Found config file ".buildkite/pipeline.yml"
{"env":{"DRY_RUN":false},"steps":[{"command":".buildkite/steps/tests.sh","name":":hammer: :linux:","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"async":true,"build":{"branch":"branch123","commit":"commit123","message":"message123"},"name":":hammer: :windows:","trigger":"agent-windows"},"wait",{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh windows 386","name":":windows: 386","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh windows amd64","name":":windows: amd64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh linux amd64","name":":linux: amd64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh linux 386","name":":linux: 386","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh linux arm","name":":linux: arm","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh linux armhf","name":":linux: armhf","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh linux arm64","name":":linux: arm64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh darwin 386","name":":mac: 386","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh darwin amd64","name":":mac: amd64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh freebsd amd64","name":":freebsd: amd64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh freebsd 386","name":":freebsd: 386","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh openbsd amd64","name":":openbsd: amd64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh openbsd 386","name":":openbsd: 386","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},{"artifact_paths":"pkg/*","command":".buildkite/steps/build-binary.sh dragonfly amd64","name":":dragonflybsd: amd64","plugins":{"docker-compose#v1.8.0":{"run":"agent"}}},"wait",{"command":".buildkite/steps/extract-agent-version-metadata.sh","name":":mag:"},"wait",{"command":".buildkite/steps/build-docker-images.sh alpine","name":":docker: alpine build"},{"command":".buildkite/steps/build-docker-images.sh ubuntu","name":":docker: ubuntu build"},{"agents":{"queue":"deploy"},"artifact_paths":"deb/**/*","command":".buildkite/steps/build-debian-packages.sh","name":":debian: build"},{"agents":{"queue":"deploy"},"artifact_paths":"rpm/**/*","command":".buildkite/steps/build-rpm-packages.sh","name":":redhat: build"},{"artifact_paths":"releases/**/*","command":".buildkite/steps/build-github-release.sh","name":":github: :hammer:","plugins":{"docker-compose#v1.8.0":{"config":"docker-compose.release.yml","run":"github-release"}}},"wait",{"command":".buildkite/steps/upload-release-steps.sh","name":":pipeline:"}]}
```

- [x] Initial spike
- [x] Feedback
- [ ] Switch to `pipeline upload --dry-run`
- [ ] Clean up code
- [ ] Tests

I'm looking for some feedback for whether we could consider adding this, and if so, some help getting it cleaned up.

### CODE REVIEW

**Comment by lox** [comment]
Conceptually I'm ok with this, although it would be great to reduce the surface area. Thoughts on `buildkite-agent pipeline upload --dump-json` instead? It's basically part of the pipeline upload flow anyway.

**Comment by toolmantim** [comment]
Thanks! Just checking, so you thinking `--dump-json` wouldn't do the actual upload tho yeah? Because I don't actually wanna do an upload in `bksr`

**Comment by keithpitt** [comment]
Yeah, I think I'd aim for an option on `pipeline upload` instead of a seperate command. I can definitely see a use case other than for use in `bksr` as well. Something along the line of "why is my pipeline upload not working, what is it even doing!?" sometimes peeps upload pipelines. and everything just comes out wrong - so it's probably useful for them to be able to run a command to see what actually gets uploading. Also it can help with getting your ENV interpolation settings right without having to re-build every time.

So having said that, instead of `--dump-json` as @lox suggest, I'd aim for `--dry-run`. Essentially meaning "instead of uploading JSON to us, dump JSON to STOUDT". I'd also want the JSON to be human readable (easy to do with this: https://golang.org/pkg/encoding/json/#example_MarshalIndent)

**Comment by toolmantim** [comment]
Cool, I'll rework this PR based on your feedback. Thanks @keithpitt & @lox

**Comment by keithpitt** [comment]
Will remove my review request for now until the next round!

**Pull request closed without merging**
