### PR TITLE
Split checkout, artifact, and plugin phases out of executor.go

### PR DESCRIPTION
**Pull request by triarius**
The file is too big for me to navigate easily. Splitting it into multiple files will make it easier to work with.

We should split it into multiple packages, but that will require more work.

I recommend reviewing commit-by-commit.

### CODE REVIEW

**Comment by moskyb** [comment]
having not read it yet: shit yes

**Comment by triarius** [comment]
@benno I was reading the diff and it seems a bit strange. I'll try to make it easier to review.

**Review by moskyb — APPROVED** [review]
send it. so happy about this

**Review by DrJosh9000 — COMMENTED** [review]
🤩

**Pull request merged**
