### PR TITLE
Add meta-data keys command

### PR DESCRIPTION
**Pull request by lox**
Implement a `buildkite-agent meta-data keys` command for listing meta-data keys:

E.g:

```bash
buildkite-agent meta-data keys # default delimited by newlines
buildkite-agent meta-data keys --delimiter ';'
```

You can use it to enumerate meta-data like:

```bash
#!/bin/bash
set -euo pipefail

buildkite-agent meta-data keys | while read -r key; do
  echo "$key: $(buildkite-agent meta-data get "$key")"
done
```

/cc @toolmantim

### CODE REVIEW

**Comment by toolmantim** [comment]
Amazing! Thanks @lox. I went to give it a test, but I don't think the `meta-data keys` subcommand exists yet yeah?

**Comment by lox** [comment]
Ok @toolmantim this should be good to go.

**Comment by toolmantim** [comment]
❤️👏🏼 So excited. Can’t wait to give this a test!

**Comment by toolmantim** [comment]
Woo, almost works a treat.

I tested it with this:

```yml
steps:
  - label: "Set the keys"
    commands: |
      cd ~/Codez/buildkite/agent
      go run main.go meta-data set foo1 bar1
      go run main.go meta-data set foo2 bar2
      go run main.go meta-data set foo3 bar3
  - wait
  - label: "Get the keys"
    commands: |
      cd ~/Codez/buildkite/agent
      echo "+++ List the keys"
      go run main.go meta-data keys
      echo "+++ Read each key"
      go run main.go meta-data keys | while read -r key; do
        echo "$$key: $$(go run main.go meta-data get "$$key")"
      done
```

The only thing I found is that I think we'll need to output the delimiter after the last item too, as the above outputs:

```

```

**Comment by lox** [comment]
@toolmantim I dunno, we don't output a trailing \n at the end of `meta-data get`, why would we for `meta-data keys`? My take is that a delimiter should occur between records, not between and after. 

I think the use-case of printing to stdout is probably pretty rare, generally it's going to be consumed by a tool, for which the trailing delimited might actually cause issues. Thoughts?

**Comment by lox** [comment]
I'm going to merge this and we can discuss in master.

**Comment by lox** [comment]
@sj26 suggested a nice thing would be to detect if it was a TTY and maybe output a trialing newline?

**Comment by toolmantim** [comment]
Did you spot that this didn't actually output all the keys though?

```
go run main.go meta-data keys | while read -r key; do
  echo "$$key: $$(go run main.go meta-data get "$$key")"
done
```

**Comment by lox** [comment]
That is unexpected 🤔

**Comment by lox** [comment]
```bash
while IFS= read -r key; do
  echo "$$key: $$(go run main.go meta-data get "$$key")"
done <(go run main.go meta-data keys)
```

Should work!

**Comment by toolmantim** [comment]
Given this is designed for bash, I figured you'd want it to work with `read`? (like in the PR description?)

i.e. the following only prints "foo1" and "foo2":

```shell
printf "foo1\nfoo2\nfoo3" | while read -r key; do
  echo "$key"
done
# foo1
# foo2
# foo3
```

This shows the same:

```shell
while IFS= read -r key; do
  echo "$key"
done < <(printf "foo1\nfoo2\nfoo3")
# foo1
# foo2
```

Echo works, because it echoes the trailing newline:

```shell
echo -e "foo1\nfoo2\nfoo3" | while read -r key; do
  echo "$key"
done
# foo1
# foo2
# foo3
```

Maybe `--delimiter` is the wrong name for the argument? 🤷🏼‍♂️ But that's why I brought it up…

**Comment by toolmantim** [comment]
Or… you could remove `--delimiter` altogether and make sure to put a newline at the end too, so it works for both `read` and just reading it in a terminal? And if people have meta-data keys containing newlines… 🤷🏼‍♂️

**Comment by lox** [comment]
I’m inclined to agree and add a trailing newline @toolmantim

**Comment by lox** [comment]
I’ll PR it

**Comment by sj26** [comment]
Yeah I think the `--delimiter` may have warped my impression, it makes sense to make it newline only, and make sure there's a trailing newline. 🙌

**Comment by lox** [comment]
This is a tricky one 🤔 I didn't understand the nuance of `read` where it returns a false value if it encounters an EOF before a newline. 

The correct way to do this with read is:

```bash
while IFS= read -r key || [[ -n "$key" ]] ; do 
  echo "$key"
done < <(printf "foo1\nfoo2\nfoo3")
```

This is because even though read returns false, the read still happens and `$key` is populated.

**Comment by toolmantim** [comment]
The extra newline still seems like a more human API to me? 🤷🏼‍♂️

**Comment by lox** [comment]
That is what I did @toolmantim!

**Comment by lox** [comment]
Was just trying to understand the bash-ness.

**Comment by lox** [comment]
See #1040.

**Comment by toolmantim** [comment]
Ah, I see! 👍🏼 We can always add a `format` json/newlines argument for machine reading?

**Comment by lox** [comment]
Yeah, I reckon.

**Pull request merged**
