### PR TITLE
Add a check for ensuring the changelog is updated

### PR DESCRIPTION
**Pull request by toolmantim**

### CODE REVIEW

**Comment by toolmantim** [comment]
I wanted to ask if we should fail the build… because the error annotation isn't visible from the GitHub pull request commit statuses? Or if we should fail the build only on a tag release? But in that case, we'd need to force push the tag to fix? Hrmmm…

**Comment by lox** [comment]
Yeah, I reckon fail the build.

**Comment by lox** [comment]
Actually, how will this work, given that we bump the version to the next version?

**Comment by toolmantim** [comment]
That’s kinda why I didnt. Maybe we need the click to unblock step to actually ask “Have you updated the Changelog? Yes no”?

**Pull request merged**
