### PR TITLE
Allow tags from the host to be automatically added

### PR DESCRIPTION
**Pull request by lox**
We presently have flags to automatically add metadata from GCP and EC2 as tags, this adds `add-host-tags` which adds some tags from the underlying host, namely `hostname`, `os` and a new one `machine-id`. 

Often people want to target a specific machine, such as in https://github.com/buildkite/agent/issues/773. This gives them an easy way to enable a per-host tag in their agent metadata. 

Machine id is calculated with https://github.com/denisbrodbeck/machineid from underlying host metadata, generally UUID's. This means if you have multiple agents on the same host you will get the same `machine-id` tag. It's portable across all the operating systems we support.

The agent also reports the `machine-id` via the agent registration api so that we can use it to co-ordinate things like shutting down all agents on a machine in future, like in https://github.com/buildkite/agent/pull/590. 

image

### CODE REVIEW

**Comment by lox** [comment]
I expected that to be much more contentious @keithpitt!

**Comment by keithpitt** [comment]
@lox as in, I might have more feedback?

**Comment by lox** [comment]
I figured there might be a reason why you didn't do this one in the first place. Something something "having host tags leads to builds that target the same agent as they previously ran on".

**Comment by keithpitt** [comment]
Oh right! I always like having an answer to something, even if it's discouraged. What you've done here makes stuff possible that was (harder) before. Fine with me!

**Comment by lox** [comment]
Agreed!

**Comment by lox** [comment]
I'm just waiting on https://github.com/denisbrodbeck/machineid/pull/4, otherwise I will use my own fork.

**Comment by petemounce** [comment]
Is there a docs PR to link to see how to use this?

**Pull request merged**
