### PR TITLE
Add ability to disable git submodules

### PR DESCRIPTION
**Pull request by toolmantim**
Allows using the agent in environments that don't have Perl, which the git submodule commands rely upon.

Related to #52

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for the quick implementation, @toolmantim!

If you change the two lines with
```sh
if [[ ! -z "${BUILDKITE_DISABLE_GIT_SUBMODULES:-}" ]]; then
```
to 
```sh
if [[ -z "${BUILDKITE_DISABLE_GIT_SUBMODULES:-}" ]]; then
```
it will work fine. :)

From the naming of the variable, I guess you wanna check if `BUILDKITE_DISABLE_GIT_SUBMODULES` is **empty**, rather than **not empty** before executing the `git submodule` calls.

**Comment by toolmantim** [comment]
Whoops, fixed. Give that a go and happy to merge into master if it works :+1:

**Comment by blueimp** [comment]
Tested and works! :+1:

**Comment by toolmantim** [comment]
@blueimp awesome! Thanks for testing. This will go out in the next agent release, which should be within the next week.

**Comment by blueimp** [comment]
Thanks! :)

**Pull request merged**
