### PR TITLE
Allow for exponential backoff between retries for artifact uploads

### PR DESCRIPTION
**Pull request by srmocher**
We occasionally get rate-limited from GCS (where we upload artifacts to) due to high load on the bucket. The suggested retry policy in such cases is to use exponential backoff between retries. https://cloud.google.com/storage/docs/exponential-backoff. We add a cli flag to optionally specify backoff strategy.

Since the agent doesn't do this currently, we're having to workaround by using `gsutil` which already does this. However, we'd like to do this through the agent so that we can see the artifacts in UI and also allow sharing of artifacts between jobs (which we've lost with using `gsutil`). 

Tested locally as follows with dummy values:
```
C02Y231UJHD2:agent sridhar.mocherla$ buildkite-agent artifact upload --job testjob --backoff-strategy exponential --endpoint localhost test.txt
2019-08-19 23:07:47 INFO   Found 1 files that match "test.txt"
2019-08-19 23:07:47 INFO   Creating (0-1)/1 artifacts
2019-08-19 23:07:47 WARN   Post localhost/jobs/testjob/artifacts: unsupported protocol scheme "" (Attempt 1/10 Retrying in 2s)
2019-08-19 23:07:49 WARN   Post localhost/jobs/testjob/artifacts: unsupported protocol scheme "" (Attempt 2/10 Retrying in 4s)
2019-08-19 23:07:53 WARN   Post localhost/jobs/testjob/artifacts: unsupported protocol scheme "" (Attempt 3/10 Retrying in 8s)
2019-08-19 23:08:01 WARN   Post localhost/jobs/testjob/artifacts: unsupported protocol scheme "" (Attempt 4/10 Retrying in 16s)
```

### CODE REVIEW

**Comment by lox** [comment]
Thanks for this! We'll review and discuss.

**Comment by lox** [comment]
We'd prefer to not have a different config for this, how about we just look for specific exit codes and use a backoff strategy in those cases?

**Comment by srmocher** [comment]
@lox Sure, I'll update the PR accordingly.

**Comment by moskyb** [comment]
Closing this as it's largely (though not entirely) superseded by https://github.com/buildkite/agent/pull/1588.

**Pull request closed without merging**
