### PR TITLE
Windows install script

### PR DESCRIPTION
**Pull request by lox**
This adds a powershell install script so that we can have users do windows installs with:

```powershell
$env:buildkiteAgentToken = "my_token"
$env:buildkiteAgentBeta = 'true'
Set-ExecutionPolicy Bypass -Scope Process -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/buildkite/agent/master/install.ps1'))
```

### CODE REVIEW

**Comment by keithpitt** [comment]
Nice! Would we still bundle the service installer with the downloadable release?

**Comment by lox** [comment]
Nah I don't think so, it's 3 lines and it's using a custom service manager. We can document that bit, this just makes the install really easy.

**Comment by lox** [comment]
Needs some more niceties from https://chocolatey.org/install.ps1.

**Comment by lox** [comment]
But it's a start!

**Pull request merged**
