### PR TITLE
Replace process.Process's bufio.Reader with a bufio.Scanner

### PR DESCRIPTION
**Pull request by lox**
The bufio.Reader is a low-level primitive, and it should be a bufio.Scanner. 

Originally part of https://github.com/buildkite/agent/pull/599.

### CODE REVIEW

**Comment by lox** [comment]
This build shows the race condition I was talking about @keithpitt: https://buildkite.com/buildkite/agent/builds/1989#1809e9a0-6279-4180-9f28-39a4c623f5ee

**Comment by lox** [comment]
There is some history in:

https://github.com/buildkite/agent/pull/430 and https://github.com/buildkite/agent/commit/e1d590a81b3e84525e0660f13cd146715b84c399

**Comment by keithpitt** [comment]
I'm 10% nervous about this change, mostly because it's super core and we're merging it right before we ship the last beta as stable. I suppose this is one of those things though that "works" or it doesn't.

Here's a question I've just thought of. How does it handle lines that are currently in progress? I.e. `rspec` appends to the current line, and when it's done, sends a "\n". Will the scanner get access to the last unfinished line?

**Comment by lox** [comment]
Yeah, I'm slightly nervous about it too. Let's defer it till 3.1! I got the tests and race fixes in the other PR, so this one is much lower down my list of cares.

**Comment by keithpitt** [comment]
@lox I'll dismiss my review for now and do a proper look when we have our 3.1 party.

**Comment by lox** [comment]
This should have no impact at all @keithpitt, it does exactly the same thing as it did before, just using the go standard library more and less code in agent. 

If you're worried about it, we could drop it in an experiment and run that for a while?

**Comment by keithpitt** [comment]
Sounds fine to me!

**Pull request merged**
