### PR TITLE
Correct encode backslashes in URLs

### PR DESCRIPTION
**Pull request by toolmantim**
When using custom S3 creds an invalid URL can be generated if filenames contain invalid URL characters (e.g. `\` or ` `). This ensures they're encoded correctly.

### CODE REVIEW

**Comment by keithpitt** [comment]
Seems legit!

**Comment by keithpitt** [comment]
(btw, is this still valid @toolmantim?)

**Comment by toolmantim** [comment]
Yep, we do this on the Ruby side now too.

But I'm thinking for Windows we should gsub '\' for '/' in the upload path, and '/' for '\' in the search and download path. It's a bit tricky, but that'll mean on Windows you're using the native paths '\' and it "just works", but internally we're storing them all with Unix path style.

If you were to mix Windows and *nix it's look like:

Win: artifact upload dir1\*
*nix: artifact download dir1/*

At the moment (and with this patch) and least it works, but it's:

Win: artifact upload dir1\file.txt
*nix: artifact download dir1\* (and the filename that gets created is called "dir1\file.txt" - the dir is part of the filename)

**Comment by toolmantim** [comment]
Doh, Github ate some slashes and stars there.

**Comment by toolmantim** [comment]
Fixed the slashes and \*'s

**Pull request merged**
