### PR TITLE
Revert "Handle pull requests with git-mirrors"

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Build is failing, reverts buildkite/agent#1308 first, then fix it later.

cc @ticky

### CODE REVIEW

**Review by yob — APPROVED** [review]
sorry @ticky, @JuanitoFatas and I were prepping a 3.26.0 release and weren't sure how to fix the failing tests :pray:

**Comment by ticky** [comment]
Wait, what was failing?

**Comment by yob** [comment]
> Wait, what was failing?

https://buildkite.com/buildkite/agent/builds/3668#6ba047ce-0eee-4d15-ba9c-366628714e51

**Comment by ticky** [comment]
Hmmm, was there some other change in master I didn’t account for? I’ll have another look

**Pull request merged**
