### PR TITLE
Add actual newlines not literal \n's to the strings

### PR DESCRIPTION
**Pull request by keithduncan**
I thought I could get away with just the quote change in https://github.com/buildkite/agent/pull/1494 but missed the newlines were literals rather than interpreted. Maybe I should have just merged #1206 😅

### CODE REVIEW

**Comment by keithduncan** [comment]
[buildkite-agent-windows-amd64.exe.zip](https://github.com/buildkite/agent/files/7087560/buildkite-agent-windows-amd64.exe.zip)

**Comment by keithduncan** [comment]
[buildkite-agent-windows-amd64.exe.zip](https://github.com/buildkite/agent/files/7087626/buildkite-agent-windows-amd64.exe.zip)

**Comment by keithduncan** [comment]
It works :tada: I found _another_ missing character, the trailing quote of the `beforeEnvFile` interpolation.

**Review by eleanorakh — APPROVED** [review]
Woohoo!!

**Pull request merged**
