### PR TITLE
Buildkite steps vs generic scripts

### PR DESCRIPTION
**Pull request by sj26**
Maybe slightly controversial: this separates our step scripts from generic scripts by following the convention we use in some of [our](https://github.com/buildkite/frontend/tree/master/.buildkite/steps) [other](https://github.com/buildkite/elastic-ci-stack-for-aws/tree/master/.buildkite/steps) [repositories](https://github.com/buildkite/buildkite-metrics/tree/master/.buildkite/steps) of using `.buildkite/steps/*` for Buildkite steps which presume use of artifacts etc, and `scripts/*` for general scripts which are called from steps but also can be used outside of Buildkite.

### CODE REVIEW

**Comment by sj26** [comment]
Woah, my master was way out of date... I'm going to fix and force push.

**Comment by sj26** [comment]
Oh, no, I think this is correct... some of the steps and scripts have very similar names and content so GitHub is showing them as re-writes. In reality most of this is `git mv scripts/*.sh .buildkite/steps/ && git mv scripts/utils/* scripts/` and updateing the pipelines and script calls.

**Comment by toolmantim** [comment]
I don't have strong feels on this! Go forth and change it as you think's best.

**Comment by lox** [comment]
Merge it quick before it gets out of date!

**Comment by sj26** [comment]
For a more sensible diff:

```diff
agent (rename-scripts) % for script in .buildkite/steps/*; do git diff HEAD~:scripts/${script##*/} $script; done
diff --git a/scripts/build-binary.sh b/.buildkite/steps/build-binary.sh
index 06a32b31..e9b0f959 100755
--- a/scripts/build-binary.sh
+++ b/.buildkite/steps/build-binary.sh
@@ -6,4 +6,4 @@ echo "--- :${1}: Building ${1}/${2}"

 rm -rf pkg

-./scripts/utils/build-binary.sh "${1}" "${2}" "${BUILDKITE_BUILD_NUMBER}"
+./scripts/build-binary.sh "${1}" "${2}" "${BUILDKITE_BUILD_NUMBER}"
diff --git a/scripts/build-debian-packages.sh b/.buildkite/steps/build-debian-packages.sh
index da483749..25ca9735 100755
--- a/scripts/build-debian-packages.sh
+++ b/.buildkite/steps/build-debian-packages.sh
@@ -39,5 +39,5 @@ for ARCH in "amd64" "386" "arm" "armhf" "arm64"; do
   chmod +x "$BINARY"

   # Build the debian package using the architectre and binary, they are saved to deb/
-  ./scripts/utils/build-debian-package.sh "$ARCH" "$BINARY" "$AGENT_VERSION" "$BUILD_VERSION"
+  ./scripts/build-debian-package.sh "$ARCH" "$BINARY" "$AGENT_VERSION" "$BUILD_VERSION"
 done
diff --git a/scripts/build-github-release.sh b/.buildkite/steps/build-github-release.sh
index 3b3245b7..e876ce50 100755
--- a/scripts/build-github-release.sh
+++ b/.buildkite/steps/build-github-release.sh
@@ -20,7 +20,7 @@ buildkite-agent artifact download "pkg/*" .
 function build() {
   echo "--- Building release for: $1"

-  ./scripts/utils/build-github-release.sh $1 $AGENT_VERSION
+  ./scripts/build-github-release.sh $1 $AGENT_VERSION
 }

 # Export the function so we can use it in xargs
diff --git a/scripts/build-rpm-packages.sh b/.buildkite/steps/build-rpm-packages.sh
index 93ecc0f7..c89af50c 100755
--- a/scripts/build-rpm-packages.sh
+++ b/.buildkite/steps/build-rpm-packages.sh
@@ -39,5 +39,5 @@ for ARCH in "amd64" "386"; do
   chmod +x "$BINARY"

   # Build the rpm package using the architecture and binary, they are saved to rpm/
-  ./scripts/utils/build-rpm-package.sh "$ARCH" "$BINARY" "$AGENT_VERSION" "$BUILD_VERSION"
+  ./scripts/build-rpm-package.sh "$ARCH" "$BINARY" "$AGENT_VERSION" "$BUILD_VERSION"
 done
diff --git a/scripts/publish-debian-package.sh b/.buildkite/steps/publish-debian-package.sh
index d7b54f0d..a3dfd71d 100755
--- a/scripts/publish-debian-package.sh
+++ b/.buildkite/steps/publish-debian-package.sh
@@ -27,5 +27,5 @@ bundle
 # Loop over all the .deb files and publish them
 for file in deb/*.deb; do
   echo "+++ Publishing $file"
-  dry_run ./scripts/utils/publish-debian-package.sh "$file" "$CODENAME"
+  dry_run ./scripts/publish-debian-package.sh "$file" "$CODENAME"
 done
diff --git a/scripts/publish-to-s3.sh b/.buildkite/steps/publish-to-s3.sh
index 44837efd..cf3ddf12 100755
--- a/scripts/publish-to-s3.sh
+++ b/.buildkite/steps/publish-to-s3.sh
@@ -43,7 +43,7 @@ done

 echo "--- :s3: Copying /$version to /latest"

-latest_version=$(aws s3 ls --region "us-east-1" "$s3_base_url/" | grep PRE | awk '{print $2}' | awk -F '/' '{print $1}' | ruby ../scripts/utils/latest_version.rb)
+latest_version=$(aws s3 ls --region "us-east-1" "$s3_base_url/" | grep PRE | awk '{print $2}' | awk -F '/' '{print $1}' | ruby ../scripts/latest_version.rb)
 latest_version_s3_url="$s3_base_url/$latest_version/"
 latest_s3_url="$s3_base_url/latest/"

diff --git a/scripts/release-homebrew.sh b/.buildkite/steps/release-homebrew.sh
index dccccc10..2e86ec73 100755
--- a/scripts/release-homebrew.sh
+++ b/.buildkite/steps/release-homebrew.sh
@@ -85,7 +85,7 @@ echo "Homebrew release version: $GITHUB_RELEASE_VERSION"
 echo "Homebrew release download URL: $DOWNLOAD_URL"
 echo "Homebrew release download SHA256: $RELEASE_SHA256"

-./scripts/utils/update-homebrew-formula.rb "$BREW_RELEASE_TYPE" "$GITHUB_RELEASE_VERSION" "$DOWNLOAD_URL" "$RELEASE_SHA256" < "$FORMULA_FILE" > "$UPDATED_FORMULA_FILE"
+./scripts/update-homebrew-formula.rb "$BREW_RELEASE_TYPE" "$GITHUB_RELEASE_VERSION" "$DOWNLOAD_URL" "$RELEASE_SHA256" < "$FORMULA_FILE" > "$UPDATED_FORMULA_FILE"

 echo "--- :rocket: Commiting new formula to master via Github Contents API"
```

**Pull request merged**
