### PR TITLE
Add BUILDKITE_DOCKER_FILE to specify the Docker file

### PR DESCRIPTION
**Pull request by toolmantim**
This way you can have each pipeline step execute in a different environment via separate Dockerfiles, for example `BUILDKITE_DOCKER_FILE=Dockerfiles/ruby` and `BUILDKITE_DOCKER_FILE=Dockerfiles/php`

### CODE REVIEW

**Comment by keithpitt** [comment]
Good change! :shipit:

**Comment by navitronic** [comment]
This is awesome! 

Thanks

**Comment by joho** [comment]
:+1:

**Comment by toolmantim** [comment]
@navitronic @joho also you can `apt-get update` for it :)

**Pull request merged**
