### PR TITLE
Switch to yaml.v2 as the YAML parser

### PR DESCRIPTION
**Pull request by keithpitt**
To fix: https://github.com/buildkite/agent/issues/510

We use github.com/ghodss/yaml as our YAML parser, which in turn uses https://github.com/go-yaml/yaml. For some reason (probably me, but I can't remember) we're using a modified version of ghodss/yaml that uses cloudfoundry-incubator/candiedyaml instead.

Switching to the proper ghodss/yaml version seems to fix the YAML parsing issue as reported in #510. I need to do some more digging why I did it like this in the first place...

### CODE REVIEW

**Comment by keithpitt** [comment]
Heh, turns out `ghodss/yaml` tried `cloudfoundry-incubator/candiedyaml` for a while, then switch back to the old version. I guess we added this package at the time they were trailing the new one :)

**Comment by sj26** [comment]
I remember having a go (hah!) at this while back and it turned out more difficult than I thought... but I don't remember why. We should definitely update it, though!

**Comment by lox** [comment]
go-yaml for sure!

**Comment by stefanmb** [comment]
@lox @sj26 @keithpitt Thank you, I can confirm this fixed the problem!

**Comment by keithpitt** [comment]
@stefanmb excellent! I even wrote a test with your example to make sure we don't break it again. It's a good YAML example to make sure that our parser can handle the more gnarly scenarios :)

**Pull request merged**
