### PR TITLE
Support plugin array configs

### PR DESCRIPTION
**Pull request by toolmantim**

### CODE REVIEW

**Comment by toolmantim** [comment]
@keithpitt wasn't sure how to do arrays of ints, and other funky stuff?

**Comment by keithpitt** [comment]
This looks pretty close! Does `[]int` work? We can just use the exact same setup that you currently have and just convert them to strings.

**Comment by toolmantim** [comment]
Yeah we can do straight ints easy. Any idea how you'd do a mix of strings and ints? My Google fu last night was failing me

**Comment by keithpitt** [comment]
I'm actually not sure what the JSON parser will do (because you can't have an array of mixed types I think). But give it a crack and see what happens!

**Comment by keithpitt** [comment]
(It may all just work)

**Comment by toolmantim** [comment]
Dang, so the int stuff never worked in the first place! Because of this: http://stackoverflow.com/questions/22343083/json-marshaling-with-long-numbers-in-golang-gives-floating-point-number

**Pull request merged**
