### PR TITLE
fallback to TASKKILL on windows

### PR DESCRIPTION
**Pull request by adill**
👋 

This may be too much of a kludge for you folks but at Discord we've been frustrated by the inability to cancel Windows jobs for ages. This fallback seems to work and I wonder if you are interested in merging it until a proper long-term fix is available?

Related issues: https://github.com/buildkite/agent/issues/213 https://github.com/buildkite/agent/issues/345

For any drive-by readers I've hosted build 2.6.6 + this fix over on [our fork](https://github.com/discordapp/buildkite-agent/releases/tag/discord-v2.6.6-1). YMMV, caveat emptor, etc.

### CODE REVIEW

**Comment by lox** [comment]
Thanks @adill! I'm sorry you've had to put up with this for so long! We're working hard on much better windows support for the v3 release. 

I don't see any reason why we can't get this into 2.6 though. @keithpitt any objections?

**Comment by lox** [comment]
Could I trouble you to add some comments to explain why this is implemented this way? 

```
// Sending Interrupt on Windows is not implemented.
// https://golang.org/src/os/exec.go?s=3842:3884#L110
```

**Comment by adill** [comment]
Looking forward to improved Windows support in v3! I've added the requested commentary. Thanks!

**Comment by lox** [comment]
Thanks very much @adill!

**Pull request merged**
